name: keeper

services:
  postgres:
    image: postgres:17
    container_name: keeper-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - keeper-postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  keeper-postgres-data:
